# .github/workflows/build.yml
name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install pygame pyinstaller
    - run: pyinstaller --onefile --windowed main.py
    - name: Ad-hoc sign macOS app
      if: matrix.os == 'macos-latest'
      run: |
        codesign --force --deep --sign - dist/main
    - uses: actions/upload-artifact@v4
      with:
        name: main-${{ matrix.os }}
        path: dist/*