# .github/workflows/build.yml
name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install pygame pyinstaller
    - run: pyinstaller --onefile --windowed vigila.py
    - uses: actions/upload-artifact@v3
      with:
        name: vigila-${{ matrix.os }}
        path: dist/*
